[package]
name = "rvalkey"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros","test-util","net","io-util"] }
